services:
  - type: web
    name: cabinet360
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        sync: false # User will need to set this
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: cabinet360
          property: host
    disk:
      name: uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1